const TRANG_THAI_PHIEU_BAO_TRI = {
  CHO_THUC_HIEN: "CHO_THUC_HIEN",
  DANG_THUC_HIEN: "DANG_THUC_HIEN",
  HOAN_THANH: "HOAN_THANH",
  QUA_HAN: "QUA_HAN",
  DA_HUY: "DA_HUY"
};

module.exports = TRANG_THAI_PHIEU_BAO_TRI;
