const TRANG_THAI_THIET_BI = {
  DANG_HOAT_DONG: "DANG_HOAT_DONG",
  DANG_BAO_TRI: "DANG_BAO_TRI",
  DANG_HONG: "DANG_HONG",
  NGUNG_HOAT_DONG: "NGUNG_HOAT_DONG",
  THANH_LY: "THANH_LY"
};

module.exports = TRANG_THAI_THIET_BI;
