const TRANG_THAI_SU_CO = {
  MOI: "MOI",
  DA_PHAN_CONG: "DA_PHAN_CONG",
  DANG_XU_LY: "DANG_XU_LY",
  CHO_LINH_KIEN: "CHO_LINH_KIEN",
  CHO_XAC_NHAN: "CHO_XAC_NHAN",
  DA_XU_LY: "DA_XU_LY",
  DA_HUY: "DA_HUY"
};

module.exports = TRANG_THAI_SU_CO;